### ISSUE TITLE
Metric Definition Grid contains Help links

### ISSUE THREAD

**Issue by philipbaileynar** [NorthArrowResearch/champ-workbench#10]
The Metric Definitions grid should contain columns for the alt help link. This could be done one of several ways:

1. New, dedicated column with the words "Online Help" or just "Help" that appear and act as hyperlinks to the corresponding help page.
1. New dedicated column with an icon that the user clicks to launch he corresponding help page. Unsure how this column would work with missing help links.
1. Reuse the metric title column or display name short hyperlinks to the corresponding help page. Metrics without valid links would just appear as text.
1. New dedicated, text column for the alt link that shows either the full URL (not recommended because it would result in a long, wide column) or just the page name.
1. New dedicated windows button column as the way to launch the help.

My preference is the first option.

**Comment by volkcj** [comment]
let's do 1 since it's most flexible.  Maybe 'online resources' instead of help.
I'm also ok with 4 and the short page names, but 1 is fine.
