### ISSUE TITLE
Database Metric Schema Typos creating bad XMLs

### ISSUE THREAD

**Issue by MattReimer** [NorthArrowResearch/champ-workbench#13]
3 Problems with the xpaths int he database that need correction:

1. Lower case "c" on channelunits
2. Tier1 should be "Name"
3. Tier2 should be "Name"

https://github.com/Riverscapes/CHaMPAutomation/commit/88c896e3ac28bd755dba42fe87cfaf53f3166e01

**Comment by philipbaileynar** [comment]
Carol implemented the visit metric change on for "ChannelUnits". I just implemented the tier 1 and 2 changes.
