### ISSUE TITLE
Edit tab/Export visit ids to .csv seems brittle...?

### ISSUE THREAD

**Issue by volkcj** [NorthArrowResearch/champ-workbench#28]
After selecting a visit and selecting this tool, the workbench  'stopped working' and shut itself down.  

I reopened the workbench and tried a second time--this time selecting three visits.  No error thrown, a file was produced, but the 'spinning' blue wheel of my cursor won't stop in workbench.   

Maybe test it one more time?

**Comment by philipbaileynar** [comment]
@volkcj  which tool / screen is this on please?

**Comment by volkcj** [comment]
Go to Edit, then select 'Export Visit IDs to .csv' option.

**Comment by volkcj** [comment]
No problems in v45.
