### ISSUE TITLE
grid doesn't sort if metrics filtered by schema (Metric Definitions view)

### ISSUE THREAD

**Issue by volkcj** [NorthArrowResearch/champ-workbench#29]
Tried sorting by 'Title' after  filtering by a schema .

**Comment by philipbaileynar** [comment]
@volkcj can I get a video or more specific set of steps to reproduce. It works for me:

1. Open Metric Definitions
1. Check on one of the schemas in the checkbox on left
1. Click any column to sort. Click again to sort in reverse direction.

**Comment by volkcj** [comment]
worked fine in v45
