### ISSUE TITLE
CHaMP Workbench Lambda Invoke

### ISSUE THREAD

**Issue by philipbaileynar** [NorthArrowResearch/champ-workbench#30]
Workbench feature to Lambda invoke automation tools.

CHaMPAutomation\tools\lambda.json

![img_20170717_111445](https://user-images.githubusercontent.com/8645379/28284853-56916054-6ae7-11e7-8911-483c50656f80.png)

**Comment by philipbaileynar** [comment]
Hey @MattReimer can I please get a detailed list of the specific items for each of the three dropdown lists in the UI mockup above:

1. Queues
1. Functions
1. Buckets

The items in these lists will get stored in a lookup table in the Workbench table so that they can be managed over time, should we need to change them.

**Comment by MattReimer** [comment]
Functions: "CHaMPWatcher" (there is only one for now)

Queues:
CHaMP-LongRun
CHaMP-Worker
QA-CHaMP-Worker

(there are more but these are the ones I want people using)

buckets:

sfr-champdata
sfr-aemdata

**Comment by philipbaileynar** [comment]
First version is working!

**Comment by volkcj** [comment]
you guys are my [heros](https://dl.dropboxusercontent.com/u/22543727/Snapshots/images.jpg)
