### ISSUE TITLE
Migrate Workbench Online Help DNS entry to GitHub IO site

### ISSUE THREAD

**Issue by philipbaileynar** [NorthArrowResearch/champ-workbench#7]
How do we handle users that have booked marked the old Hugo Workbench web site at `workbench.northarrowresearch.com`? Options:

1. Do nothing. Leave stale, outdated, misleading content online.
1. Strip all pages from the old site and leave just a simple text message linking to the new GHIO wiki.
1. More fancy redirect process for automatically redirecting users to the GHIO wiki.
1. Switch the DNS entry to GHIO wiki. The individual page URLs that people might have book marked will still break, but at least they will get a 404 error *on the actual, correct site* where they need to be. Most folks can figure out getting to the root of that site from the 404 page.

**Comment by MattReimer** [comment]
I've pointed the CNAME properly as per our discussion
