### ISSUE TITLE
YouTube links in documentation

### ISSUE THREAD

**Issue by philipbaileynar** [NorthArrowResearch/champ-workbench#9]
The YouTube links in the Workbench wiki still use Hugo and need to be updated to Jekyll. There's an example at the bottom of this page:

[https://northarrowresearch.github.io/champ-workbench/Technical_Reference/Data_Menu/custom_visits.html](https://northarrowresearch.github.io/champ-workbench/Technical_Reference/Data_Menu/custom_visits.html)

**Comment by MattReimer** [comment]
There's a new and exciting way to do youtube vides in Jekyll:

```html
 <div class="flex-video">
 <iframe src="https://www.youtube.com/embed/9ocXMfrf77U" frameborder="0" allowfullscreen=""></iframe>
</div>
```
